wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1696864192.331263
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 103
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.9.17
      5: 0.15.9
      6: 4.32.1
      8:
      - 1
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
